### ISSUE TITLE
coco stuff

### ISSUE THREAD

**Issue by kevinwei0410** [WalBouss/SenFormer#1]
hi, Im student in taiwan

Does the model not support for "coco-stuff" yet ?
the file : SenFormer\mmseg\core\evaluation\classesnames
which only have three different types of dataset, 

dataset_aliases = {
    'cityscapes': ['cityscapes'],
    'ade': ['ade', 'ade20k'],
    'voc': ['voc', 'pascal_voc', 'voc12', 'voc12aug']
}

...?

**Comment by WalBouss** [comment]
Hi,
The repository does support COCO-Stuff dataset. You can train SenFormer from scratch on COCO-Stuff or download pretrained weights from this repo and evaluate on COCO-stuff by running this command:
```python
python tools/test.pysenformer_configs/senformer/coco-stuff10k/senformer_fpnt_r50_512x512_80k_coco.py /path/to/checkpoint_file
```

But you are right the [class_names.py](https://github.com/WalBouss/SenFormer/blob/master/mmseg/core/evaluation/class_names.py) did not contain coco's classes and palette.
However, since it's only used in  [image_demo.py](https://github.com/WalBouss/SenFormer/blob/master/demo/image_demo.py), it does not affect the rest of the repo.
Anyway, I have updated the affected files and image_demo.py should now work on COCO-Stuff too:

```python 
python demo/image_demo.py ${IMAGE_FILE} ${CONFIG_FILE} ${CHECKPOINT_FILE} --classes=coco --palette=coco
```
Hope that helps

**Comment by kevinwei0410** [comment]
hi, 
Many thanks for your reply and the tutorials.

I run your model to do semantic segmentation on my custom data set, and the performance is impressive.
Therefore, I can get  wonderful training data. It help me smoother to develop my final project.
In the final report, I will attach the link of your github and introduce how the training data was generated.


I hope everything goes well with your work and research.
best regards,

**Comment by WalBouss** [comment]
Glad it helped! 

Good luck with your project, and feel free to reach out if you encounter additional complications with the code.
Best,
